language: python

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

# branches:
#   only:
#     - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: "busted spec.lua"

notifications:
  # webhooks:
  #   - http://my-url/travis-results
  # recipients:
  #   - engineering@company.com
  email:
    on_success: change
    on_failure: always